name: SketchMap
version: 1.3.2
main: com.mcplugindev.slipswhitley.sketchmap.SketchMapPlugin
softdepend: [ Vault ]
commands:
  sketchmap:
    description: SketchMap Core Command
    usage: /sketchmap help
