name: SketchMap
version: 1.5.0
main: com.mcplugindev.slipswhitley.sketchmap.SketchMapPlugin
depend: [ Vault ]
commands:
  sketchmap:
    description: SketchMap Core Command
    usage: /sketchmap help
